// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaAIIISq9xHeMM1aH-bk2zrn-rYmuXKdY',
    appId: '1:971391628451:web:1f0751abd1cad401087b16',
    messagingSenderId: '971391628451',
    projectId: 'aviator-bot-3',
    authDomain: 'aviator-bot-3.firebaseapp.com',
    storageBucket: 'aviator-bot-3.firebasestorage.app',
    measurementId: 'G-XQVZCW0PCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Wlama0IMTqqgcpzluXi4m46qEdV9iPE',
    appId: '1:971391628451:android:7c6903641f2d209d087b16',
    messagingSenderId: '971391628451',
    projectId: 'aviator-bot-3',
    storageBucket: 'aviator-bot-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPK9cZhy4dK_lzOXg_QYNWSmV_oCF7HJU',
    appId: '1:971391628451:ios:719a7bd0cd57eef1087b16',
    messagingSenderId: '971391628451',
    projectId: 'aviator-bot-3',
    storageBucket: 'aviator-bot-3.firebasestorage.app',
    iosClientId: '971391628451-5hg6a5sa5828c2ghiso243673ju8ifbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.defaultApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPK9cZhy4dK_lzOXg_QYNWSmV_oCF7HJU',
    appId: '1:971391628451:ios:719a7bd0cd57eef1087b16',
    messagingSenderId: '971391628451',
    projectId: 'aviator-bot-3',
    storageBucket: 'aviator-bot-3.firebasestorage.app',
    iosClientId: '971391628451-5hg6a5sa5828c2ghiso243673ju8ifbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.defaultApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaAIIISq9xHeMM1aH-bk2zrn-rYmuXKdY',
    appId: '1:971391628451:web:85afaa26847fbf94087b16',
    messagingSenderId: '971391628451',
    projectId: 'aviator-bot-3',
    authDomain: 'aviator-bot-3.firebaseapp.com',
    storageBucket: 'aviator-bot-3.firebasestorage.app',
    measurementId: 'G-2EG2WMQTZX',
  );
}
